// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Elders.Multithreading.Scheduler")]
[assembly: AssemblyDescriptionAttribute("The idea is to create a dedicated threads for a particular work. The WorkPool class does not use the standard .NET thread pool.")]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("Elders.Multithreading.Scheduler")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2015")]
[assembly: AssemblyVersionAttribute("1.1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.1.0+1.Branch.master.Sha.25442a58c8498465a9335b9bb288b5450d3d2cba")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.1.0.0";
    }
}
