// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Elders.Multithreading.Scheduler")]
[assembly: AssemblyDescriptionAttribute("Elders.Multithreading.Scheduler")]
[assembly: GuidAttribute("b422fc04-22de-40ec-978f-bf89fc017411")]
[assembly: AssemblyProductAttribute("Elders.Multithreading.Scheduler")]
[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0";
    }
}
